name: C/C++ CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make build
      run: make _build
    - name: make test
      run: make _test
    - name: make clean
      run: make clean
